{
  pkgs,
  userConfig,
  homeDir,
  ...
}: {
  imports = [
    # Machine-specific hardware config generated by `nixos-generate-config`.
    # Copy /etc/nixos/hardware-configuration.nix from the target machine into
    # this directory (it is git-tracked alongside this file).
    ./hardware-configuration.nix
  ];

  # Nix settings (mirrors the darwin host)
  nix = {
    package = pkgs.nix;
    settings = {
      experimental-features = "nix-command flakes";
      download-buffer-size = 524288000;
    };
    optimise.automatic = true;
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 14d";
    };
  };

  # Boot loader — adjust if the machine uses GRUB/BIOS instead of UEFI.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = "nixos-desktop";
  networking.networkmanager.enable = true;

  time.timeZone = "Europe/Stockholm";
  i18n.defaultLocale = "en_US.UTF-8";

  # User configuration
  users.users.${userConfig.name} = {
    isNormalUser = true;
    description = userConfig.fullName;
    home = homeDir;
    shell = pkgs.fish;
    extraGroups = ["wheel" "networkmanager" "docker" "video" "audio"];
  };

  # Fish must be enabled at the system level to be a valid login shell
  programs.fish.enable = true;

  # Hyprland (Wayland tiling compositor) — the per-user config lives in
  # home-manager/programs-linux/hyprland
  programs.hyprland.enable = true;

  # Login manager with Wayland support for the Hyprland session
  services.displayManager.sddm = {
    enable = true;
    wayland.enable = true;
  };

  # Audio
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    pulse.enable = true;
  };

  # Docker daemon (on macOS this is provided by colima)
  virtualisation.docker.enable = true;

  fonts.packages = with pkgs; [
    jetbrains-mono
    nerd-fonts.symbols-only
  ];

  environment.systemPackages = with pkgs; [
    git
    vim
    wget
  ];

  # Used for backwards compatibility, please read the changelog before changing.
  # https://nixos.org/manual/nixos/stable/options.html#opt-system.stateVersion
  system.stateVersion = "25.05";
}
