{
  pkgs,
  userConfig,
  homeDir,
  ...
}: {
  imports = [
    # Machine-specific hardware config generated by `nixos-generate-config`.
    # Copy /etc/nixos/hardware-configuration.nix from the target machine into
    # this directory (it is git-tracked alongside this file).
    ./hardware-configuration.nix
  ];

  # Nix settings (mirrors the darwin host)
  nix = {
    package = pkgs.nix;
    settings = {
      experimental-features = "nix-command flakes";
      download-buffer-size = 524288000;
    };
    optimise.automatic = true;
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 14d";
    };
  };

  # Boot loader — adjust if the machine uses GRUB/BIOS instead of UEFI.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Latest kernel (carried over from the original /etc/nixos config).
  boot.kernelPackages = pkgs.linuxPackages_latest;

  networking.hostName = "nixos-desktop";
  networking.networkmanager.enable = true;

  time.timeZone = "Europe/Stockholm";
  i18n.defaultLocale = "en_US.UTF-8";
  # Swedish formats for dates, numbers, currency, etc.
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "sv_SE.UTF-8";
    LC_IDENTIFICATION = "sv_SE.UTF-8";
    LC_MEASUREMENT = "sv_SE.UTF-8";
    LC_MONETARY = "sv_SE.UTF-8";
    LC_NAME = "sv_SE.UTF-8";
    LC_NUMERIC = "sv_SE.UTF-8";
    LC_PAPER = "sv_SE.UTF-8";
    LC_TELEPHONE = "sv_SE.UTF-8";
    LC_TIME = "sv_SE.UTF-8";
  };

  # User configuration
  users.users.${userConfig.name} = {
    isNormalUser = true;
    description = userConfig.fullName;
    home = homeDir;
    shell = pkgs.fish;
    extraGroups = ["wheel" "networkmanager" "docker" "video" "audio"];
  };

  # Fish must be enabled at the system level to be a valid login shell
  programs.fish.enable = true;

  # Hyprland (Wayland tiling compositor) — the per-user config lives in
  # home-manager/programs-linux/hyprland
  programs.hyprland.enable = true;

  # Login manager: greetd + tuigreet. SDDM was replaced because its systemd
  # session tracking (wayland-session-bindpid@.service) failed to launch the
  # Hyprland Wayland session. tuigreet runs in the console and starts Hyprland
  # directly, which avoids that machinery entirely.
  services.greetd = {
    enable = true;
    settings.default_session = {
      command = "${pkgs.tuigreet}/bin/tuigreet --time --remember --cmd Hyprland";
      user = "greeter";
    };
  };

  # Audio
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true; # 32-bit audio for Steam/Proton games
    pulse.enable = true;
  };

  # Printing (CUPS)
  services.printing.enable = true;

  # SSH — escape hatch so a broken display session can be debugged remotely.
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = true;
  };

  # Docker daemon (on macOS this is provided by colima)
  virtualisation.docker.enable = true;

  # GPU drivers — 32-bit support is required by Steam/Proton games
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  # Chromium extensions are force-installed via the system managed-policy
  # (ExtensionInstallForcelist). home-manager's programs.chromium.extensions
  # does not work on Linux — Chromium only loads force-installed extensions
  # from system policy dirs, which a user-level tool cannot write to.
  programs.chromium = {
    enable = true;
    extensions = [
      # uBlock Origin Lite (MV3). The original uBlock Origin is MV2, which
      # Chromium >= 139 refuses to run (the ExtensionManifestV2Availability
      # policy is no longer honored) and the Web Store no longer hosts, so
      # force-installing it fails silently.
      "ddkjiahejlhfcafbddmgiahcphecmpfh"
      "dbepggeogbaibhgnhhndojpepiihcmeb" # Vimium (vim keybindings)
    ];
  };

  # Steam + Proton. `steam` is unfree (allowUnfree is set in the flake).
  programs.steam = {
    enable = true;
    remotePlay.openFirewall = true; # Steam Remote Play
    dedicatedServer.openFirewall = true; # Source dedicated server ports
    # Proton ships with Steam; add Proton-GE as an extra compatibility tool.
    # Select it per-game via Steam > Properties > Compatibility.
    extraCompatPackages = [pkgs.proton-ge-bin];
  };

  fonts.packages = with pkgs; [
    jetbrains-mono
    nerd-fonts.symbols-only
  ];

  environment.systemPackages = with pkgs; [
    git
    vim
    wget
  ];

  # Used for backwards compatibility, please read the changelog before changing.
  # https://nixos.org/manual/nixos/stable/options.html#opt-system.stateVersion
  system.stateVersion = "26.05";
}
