name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check Nix formatting
        run: |
          nix profile install nixpkgs#nixpkgs-fmt
          nix run nixpkgs#nixpkgs-fmt -- --check **/*.nix

      - name: Check Flake
        run: |
          nix flake show